server:
  port: ${SERVER_PORT:8001}

security:
  jwt:
    public-key: classpath:jwt-signing-public-key.txt

service:
  stripeKey: sk_test_51HyGx6G9R9y827ntfKTizO243LzKHnaNIucO8i7apU0zuTIE5iNAes6l64aoWczGwiCnnBNsvvrgS95nfpbWa2cw00FnScmrhd

spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  zipkin:
    base-url: http://${ZIPKIN_HOST:localhost:9411}
    enabled: true
    service:
      name: bookstore-payment-service
    message-timeout: 10
  sleuth:
    sampler:
      probability: 1.0
  flyway:
    table: payment_service_flyway_history
    baseline-on-migrate: true
    baseline-version: 0.9
  main:
    allow-bean-definition-overriding: true
  hateoas:
    use-hal-as-default-json-media-type: false

logging:
  level:
    com.devd.spring.*: DEBUG

management:
  endpoint:
    hystrix:
      stream:
        enabled: true

---

spring:
  profiles: postgres
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: root
    url: jdbc:postgresql://localhost/postgres
    platform: postgres
    initialization-mode: always
    continue-on-error: true
    jpa:
      show-sql: false
      generate-ddl: auto
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      database: postgresql
      properties:
        hibernate:
          temp:
            use_jdbc_metadata_defaults: false;
      database-platform: org.hibernate.dialect.PostgreSQL9Dialect

---

spring:
  profiles: docker
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
    open-in-view: true
    generate-ddl: true
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://bookstore-postgres:5432/postgres
    username: postgres
    password: root